/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Resources;

import StudentHome.StudentHome;
import Login.Login;
import TeacherSetResources.AssigningAResource;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.util.ArrayList;
/**
 *
 * @author 4-EBULL
 */
public class Resources extends javax.swing.JFrame {

    /**
     * Creates new form Resources
     */
    public Resources() {
        initComponents();
        ArrayList<String> ListOfTopics = VeiwResources.SetBox();
        for (int i = 0; i < ListOfTopics.size(); i ++ ){
            jComboBoxTopics.addItem(ListOfTopics.get(i));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResourceList = new javax.swing.JList<>();
        jSelect = new javax.swing.JButton();
        jComboBoxTopics = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtHome.setText("Home");
        jtxtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Resources");

        jResourceList.setForeground(new java.awt.Color(51, 153, 255));
        jResourceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickedOnUrl(evt);
            }
        });
        jScrollPane1.setViewportView(jResourceList);

        jSelect.setText("Select");
        jSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectActionPerformed(evt);
            }
        });

        jComboBoxTopics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        jLabel2.setText("Topics: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxtHome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jSelect)))
                        .addContainerGap(664, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtHome)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTopics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHomeActionPerformed
        StudentHome submitButton = new StudentHome();  
        submitButton.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jtxtHomeActionPerformed

    private void jSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectActionPerformed
        String ResourceType = jComboBoxTopics.getSelectedItem().toString();
        ListModel<String> URLS = AssigningAResource.ResourceListToScreen(ResourceType);
        jResourceList.setModel(URLS);
    }//GEN-LAST:event_jSelectActionPerformed

    private void MouseClickedOnUrl(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickedOnUrl
        // incase want to redo this in future i did mouseclick -> handlers. 
        // then i did double just cause i felt like it 
        // get location on screen and then the index on the list
        // -1 = bad cause means return nothing so do if statement for it 
        // make sure it is only the url or its gonna mess up. i had to get rid of 4:
        // then try desktop 
        // on and set colour on properties to blue to give the universal URL colour

        // this is for double click 
        if ( evt.getClickCount() == 2) {
            // set it to null cause the later line was having an issue with it not being initalised 
            String url = null;
            
            // evt = the mouse event object 'click'
            int index = jResourceList.locationToIndex(evt.getPoint());
            // ive put this cause index returns -1 if not found
            if ( index !=-1) {
                // gets the rest of the url after https: cause i put a num infornt of it before hand 
                // cause i reused code from teacher.set resource
                url = jResourceList.getModel().getElementAt(index);
                url = url.substring(url.indexOf("http"));
            }

            try {
                java.awt.Desktop.getDesktop().browse(new java.net.URI(url));
            }
            catch ( Exception e ){
                // brings up neew temp screen
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid URL");
            } 
        }
    }//GEN-LAST:event_MouseClickedOnUrl

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resources().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxTopics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jResourceList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSelect;
    private javax.swing.JButton jtxtHome;
    // End of variables declaration//GEN-END:variables
}
