/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quizzes;
import StudentHome.StudentHome;
import Login.Login;
import java.util.ArrayList;

/**
 *
 * @author elois
 */
public class Quizzes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quizzes.class.getName());
    private QuizQuestions quiz;
    private boolean targeted;
    /**
     * Creates new form Quizzes
     */
    
    public static class QuizDetails{
        public static ArrayList<String> ListOfQuestionsWrong = new ArrayList(); 
        public static ArrayList<String> ListOfAnswers = new ArrayList(); 
        public static Float CurrentStats;
        public static int questionsDone;
        public static String RealAnswer;
    }
    
    public Quizzes() {
        
        initComponents();   
        targeted = false;
        quiz = new QuizQuestions();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtQuizQuestion = new javax.swing.JTextField();
        jtxtUserAnswer = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jtxtHome = new javax.swing.JButton();
        jtxtCheatToGetAnswer = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jLabelStats = new javax.swing.JLabel();
        jButtonRandom = new javax.swing.JRadioButton();
        jButtonTargeted = new javax.swing.JRadioButton();
        jPanelCorrrectOrWrong = new javax.swing.JPanel();
        jLabelMark = new javax.swing.JLabel();
        jFinishQuiz = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();
        lCorrectAnswer = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Quizzes");

        jtxtQuizQuestion.setEditable(false);
        jtxtQuizQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuizQuestionActionPerformed(evt);
            }
        });

        jtxtUserAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserAnswerActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jtxtHome.setText("Home");
        jtxtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHomeActionPerformed(evt);
            }
        });

        jLabelQuestion.setText("Question: 1");

        jLabelStats.setText("Stats : 0%");

        buttonGroup2.add(jButtonRandom);
        jButtonRandom.setText("RandomQuiz");
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });

        buttonGroup2.add(jButtonTargeted);
        jButtonTargeted.setText("TargetedQuiz");
        jButtonTargeted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTargetedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCorrrectOrWrongLayout = new javax.swing.GroupLayout(jPanelCorrrectOrWrong);
        jPanelCorrrectOrWrong.setLayout(jPanelCorrrectOrWrongLayout);
        jPanelCorrrectOrWrongLayout.setHorizontalGroup(
            jPanelCorrrectOrWrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanelCorrrectOrWrongLayout.setVerticalGroup(
            jPanelCorrrectOrWrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabelMark.setText("Marked:");

        jFinishQuiz.setText("Finish");
        jFinishQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishQuizActionPerformed(evt);
            }
        });

        lCorrectAnswer.setText("Correct Answer: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCheatToGetAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(168, 168, 168)
                            .addComponent(jButtonSubmit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFinishQuiz))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelCorrrectOrWrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuestion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRandom)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jtxtHome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonTargeted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMark, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(220, 220, 220))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtQuizQuestion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtUserAnswer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRandom))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jtxtHome)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jPanelCorrrectOrWrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButtonTargeted)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelQuestion)
                        .addComponent(jLabelStats))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelMark)))
                .addGap(18, 18, 18)
                .addComponent(lCorrectAnswer)
                .addGap(33, 33, 33)
                .addComponent(jtxtQuizQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtUserAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jFinishQuiz))
                .addGap(54, 54, 54)
                .addComponent(jtxtCheatToGetAnswer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserAnswerActionPerformed
        
        
        //take user input then 
        //boolean check = CheckAnswers(3,5);
        
       
    }//GEN-LAST:event_jtxtUserAnswerActionPerformed

    private void jtxtQuizQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuizQuestionActionPerformed
        
        // move to the main when u get the connection to work 
    }//GEN-LAST:event_jtxtQuizQuestionActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // to check it is next not submit
        String ButtonText = jButtonSubmit.getText();
        // this is to move onto the next question
        if ("Next".equals(ButtonText)) {
            jButtonSubmit.setText("Submit");
            jLabelMark.setText("");
            lCorrectAnswer.setText("");
            if ( targeted == false ) {
                quiz = new QuizQuestions();
                jtxtQuizQuestion.setText(quiz.RandomQuiz());
            }
            else {
                jtxtQuizQuestion.setText(quiz.TargetedQuestions());
            }
        }
        //this is to 
        else {
            jButtonSubmit.setText("Next");
            boolean correct;
            String ActualAnswer = null;
            // does the on screen stuff 
            String Question = jtxtQuizQuestion.getText();
            String answer = (jtxtUserAnswer.getText());
            // need to get rid of any spaces that could be inputted
        
            if ("".equals(answer)){
                jWarning.setText("Please Enter An Answer");
            }
            else{
                // this is for the random quiz
                // returns 1 if correct
                // and returns actual answer
                if ( targeted == false) {
                    correct = quiz.CheckAnswer(answer);
                    if (correct){
                        correct = true;
                    }
                    else {
                        correct = false;
                    }
                }

                // this is for specific quiz
                else{
                    correct = quiz.CheckTargetedAnswer(answer, Question);
                }
                // adds wrong answers to the list for quiz output
                if (!correct){
                    QuizDetails.ListOfAnswers.add(ActualAnswer);
                }
            
                if ( correct == true) {            
                    jLabelMark.setText("Marked: Correct");
                }
                else {
                    jLabelMark.setText("Marked: Incorrect");
                    String QuizQuestion = jtxtQuizQuestion.getText();
                    QuizDetails.ListOfQuestionsWrong.add(QuizQuestion);
                }
           
                int count = QuizQuestions.count();
                // -1 cause it displays the current questions ur on not hte one youve done
                QuizDetails.questionsDone = count - 1;
            
                 jLabelQuestion.setText("Question: " + count);
                float stats = QuizQuestions.CountingQuizStats(count-1,correct);
                // updates the temp stored data of this quiz
                QuizDetails.CurrentStats = stats;
                jLabelStats.setText ("Stats: " + stats + "%");
            
                int Student_id = Login.InfoOfUserForThisLoginSession.StudentId ;
                /// get topicID
                QuizQuestions quiz = new QuizQuestions();
                int topicID = quiz.ReturnTopicID(Question);
                /// adds one to the numofquestionsdoen in databse for specific topic
                quiz.AddOneToNumOfQuestionsDone(topicID, Student_id);
                quiz.updateStats(correct, topicID, Student_id);
                lCorrectAnswer.setText("Correct Answer: "  + QuizDetails.RealAnswer );
                jtxtUserAnswer.setText("");
                //int num = Integer.valueOf(jLabelQuestion.getText());
                //jLabelQuestion.setText("Question: " + ( num + 1 ));
            }
            
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jtxtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHomeActionPerformed
        StudentHome submitButton = new StudentHome();  
        submitButton.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHomeActionPerformed

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        targeted = false;
        jtxtQuizQuestion.setText(quiz.RandomQuiz());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jButtonTargetedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTargetedActionPerformed
        targeted = true; 
        jtxtQuizQuestion.setText(quiz.TargetedQuestions());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTargetedActionPerformed

    private void jFinishQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishQuizActionPerformed
        QuizOutput NewScreen = new QuizOutput();  
        NewScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFinishQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quizzes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jButtonRandom;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JRadioButton jButtonTargeted;
    private javax.swing.JButton jFinishQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMark;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelStats;
    private javax.swing.JPanel jPanelCorrrectOrWrong;
    private javax.swing.JLabel jWarning;
    private javax.swing.JLabel jtxtCheatToGetAnswer;
    private javax.swing.JButton jtxtHome;
    private javax.swing.JTextField jtxtQuizQuestion;
    private javax.swing.JTextField jtxtUserAnswer;
    private javax.swing.JLabel lCorrectAnswer;
    // End of variables declaration//GEN-END:variables
}
