/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quizzes;
import StudentHome.StudentHome;
import Login.Login;
import java.util.ArrayList;
import ViewAssignmentsScreen.ViewAssignmentsScreen;
import javax.swing.JOptionPane;

/**
 *
 * @author elois
 */
public class Quizzes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quizzes.class.getName());
    private QuizQuestions quiz;
    private boolean targeted;
    boolean ToDoAssignmnet;
    /**
     * Creates new form Quizzes
     */
    
    public static class QuizDetails{
        // for personal set quizzes
        public static ArrayList<String> ListOfQuestionsWrong = new ArrayList(); 
        public static ArrayList<String> ListOfAnswers = new ArrayList(); 
        public static ArrayList<String> ListOfUserAnswers = new ArrayList(); 
        public static Float CurrentStats;
        public static int questionsDone;
        public static String RealAnswer;
    }
    

    public Quizzes() {
        initComponents();   
        targeted = false;
        quiz = new QuizQuestions();
        
        // resets the quiz variables
        DoAssignment Assign = new DoAssignment();
        Assign.ResetVariables();
        
        ToDoAssignmnet = ViewAssignmentsScreen.InfoForAssignment.Assignment;
        // sets it back to false cause then when they want to do a normal quiz its false
        ViewAssignmentsScreen.InfoForAssignment.Assignment = false;
        
        if (ToDoAssignmnet){
            jQuizzesLabel.setText("Assignment");
            jButtonRandom.setVisible(false);
            jButtonTargeted.setVisible(false);
            jButtonSubmit.setText("Start");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jQuizzesLabel = new javax.swing.JLabel();
        jtxtQuizQuestion = new javax.swing.JTextField();
        jtxtUserAnswer = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jtxtHome = new javax.swing.JButton();
        jLabelQuestion = new javax.swing.JLabel();
        jLabelStats = new javax.swing.JLabel();
        jButtonRandom = new javax.swing.JRadioButton();
        jButtonTargeted = new javax.swing.JRadioButton();
        jPanelCorrrectOrWrong = new javax.swing.JPanel();
        jLabelMark = new javax.swing.JLabel();
        jFinishQuiz = new javax.swing.JButton();
        lCorrectAnswer = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jQuizzesLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jQuizzesLabel.setText("Quizzes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 5, 0, 0);
        getContentPane().add(jQuizzesLabel, gridBagConstraints);

        jtxtQuizQuestion.setEditable(false);
        jtxtQuizQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuizQuestionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 37, 0, 0);
        getContentPane().add(jtxtQuizQuestion, gridBagConstraints);

        jtxtUserAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserAnswerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 37, 0, 0);
        getContentPane().add(jtxtUserAnswer, gridBagConstraints);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 27, 0);
        getContentPane().add(jButtonSubmit, gridBagConstraints);

        jtxtHome.setText("Home");
        jtxtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 49, 0, 0);
        getContentPane().add(jtxtHome, gridBagConstraints);

        jLabelQuestion.setText("Question: 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 37, 0, 0);
        getContentPane().add(jLabelQuestion, gridBagConstraints);

        jLabelStats.setText("Stats : 0%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        getContentPane().add(jLabelStats, gridBagConstraints);

        buttonGroup2.add(jButtonRandom);
        jButtonRandom.setText("RandomQuiz");
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        getContentPane().add(jButtonRandom, gridBagConstraints);

        buttonGroup2.add(jButtonTargeted);
        jButtonTargeted.setText("TargetedQuiz");
        jButtonTargeted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTargetedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 49, 0, 0);
        getContentPane().add(jButtonTargeted, gridBagConstraints);

        javax.swing.GroupLayout jPanelCorrrectOrWrongLayout = new javax.swing.GroupLayout(jPanelCorrrectOrWrong);
        jPanelCorrrectOrWrong.setLayout(jPanelCorrrectOrWrongLayout);
        jPanelCorrrectOrWrongLayout.setHorizontalGroup(
            jPanelCorrrectOrWrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanelCorrrectOrWrongLayout.setVerticalGroup(
            jPanelCorrrectOrWrongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 38;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 58, 0, 0);
        getContentPane().add(jPanelCorrrectOrWrong, gridBagConstraints);

        jLabelMark.setText("Marked:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 37, 0, 0);
        getContentPane().add(jLabelMark, gridBagConstraints);

        jFinishQuiz.setText("Finish");
        jFinishQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishQuizActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 46, 27, 0);
        getContentPane().add(jFinishQuiz, gridBagConstraints);

        lCorrectAnswer.setText("Correct Answer: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 37, 0, 0);
        getContentPane().add(lCorrectAnswer, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserAnswerActionPerformed

    }//GEN-LAST:event_jtxtUserAnswerActionPerformed

    private void jtxtQuizQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuizQuestionActionPerformed

    }//GEN-LAST:event_jtxtQuizQuestionActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // checks if it is an assignment 
        // if assignment - it uses the same screen it just has it to the set topic and count down of questions

        if (ToDoAssignmnet){
            // checks theres questions left in the assignment
            if (!(ViewAssignmentsScreen.InfoForAssignment.NumOfAssignmentQuestionsLeft <= 0)){
                
                String ButtonText = jButtonSubmit.getText();
                // this is to move onto the next question
                if ("Next".equals(ButtonText) || "Start".equals(ButtonText)) {
                    jButtonSubmit.setText("Submit");
                    jLabelMark.setText("");
                    lCorrectAnswer.setText("");
                    // checks what topic the assignments on 
                    String TopicForAssignment = ViewAssignmentsScreen.InfoForAssignment.Topic;
                    if ("All".equals(TopicForAssignment)){
                        // do a random quiz for this
                        RandomQuiz quiz = new RandomQuiz();
                        jtxtQuizQuestion.setText(quiz.RandomQuiz());
                    }
                    else {
                        TargetedQuiz TQuiz = new TargetedQuiz();
                        jtxtQuizQuestion.setText(TQuiz.TargetedQuestions(true, TopicForAssignment));
                    }

                }
                // user submits answer to be checked 
                else {
                    boolean correct;
                    // does the questions left count
                    ViewAssignmentsScreen.InfoForAssignment.NumOfAssignmentQuestionsLeft = ViewAssignmentsScreen.InfoForAssignment.NumOfAssignmentQuestionsLeft - 1;
                    // checks if the answer is correct
                    String Question = jtxtQuizQuestion.getText();
                    String answer = (jtxtUserAnswer.getText());
                    correct = quiz.CheckAnswer(answer, Question);
                    // marks the answer 
                    if ( correct == true) {            
                        jLabelMark.setText("Marked: Correct");
                    }
                    else {
                        jLabelMark.setText("Marked: Incorrect");
                        // if incorrect it adds it to the lsit of quesrtions that were wrong
                        String QuizQuestion = jtxtQuizQuestion.getText();
                        QuizDetails.ListOfQuestionsWrong.add(QuizQuestion);
                    }
                    int count = QuizQuestions.count(false);
                    // -1 cause it displays the current questions ur on not hte one youve done
                    // amount of questions done
                    QuizDetails.questionsDone = count;
                    // questions left to do 
                    jLabelQuestion.setText("Questions left: " + ViewAssignmentsScreen.InfoForAssignment.NumOfAssignmentQuestionsLeft);
                    float stats = QuizQuestions.CountingQuizStats(count,correct, false);
                    // updates the temp stored data of this quiz
                    QuizDetails.CurrentStats = stats;
                    jLabelStats.setText ("Stats: " + stats + "%");
            
                    int Student_id = Login.InfoOfUserForThisLoginSession.StudentId ;
                    /// get topicID
                    TargetedQuiz TQuiz = new TargetedQuiz();
                    int topicID = TQuiz.ReturnTopicID(Question);
                    /// adds one to the numofquestionsdoen in databse for specific topic
                    quiz.AddOneToNumOfQuestionsDone(topicID, Student_id);
                    quiz.updateStats(correct, topicID, Student_id);
                    lCorrectAnswer.setText("Correct Answer: "  + QuizDetails.RealAnswer );
                    jtxtUserAnswer.setText("");
                    //int num = Integer.valueOf(jLabelQuestion.getText());
                    //jLabelQuestion.setText("Question: " + ( num + 1 ));
                    jButtonSubmit.setText("Next");
                    
                    
                    // update database 
                    // change num of quesitons done

                    int Assignmentid = ViewAssignmentsScreen.InfoForAssignment.Assignmentid;
                    int AssignedID = ViewAssignmentsScreen.InfoForAssignment.Assignedid;
                    
                    // parameters, assignmentid assignedid, current num of questions
                    DoAssignment Do = new DoAssignment();
                    Do.AddOneToQuestionsDone(Assignmentid, AssignedID);
                }
                
            }
            else {
                // set assignment to done cause there is no questions left
                DoAssignment DoAssigned = new DoAssignment();
                DoAssigned.setAssignmentToDone(ViewAssignmentsScreen.InfoForAssignment.Assignmentid,
                        ViewAssignmentsScreen.InfoForAssignment.Assignedid);
                // moves to finish screen 
                QuizOutput NewScreen = new QuizOutput();  
                NewScreen.setVisible(true);
                this.dispose();
                
            }
        }
        

        
        // this means it is not an assignment and just a normal quiz 
        else {
            String ButtonText = jButtonSubmit.getText();
            // this is to move onto the next question
            if ("Next".equals(ButtonText)) {
                jButtonSubmit.setText("Submit");
                jLabelMark.setText("");
                lCorrectAnswer.setText("");
                if ( targeted == false ) {
                    RandomQuiz quiz = new RandomQuiz();
                    jtxtQuizQuestion.setText(quiz.RandomQuiz());
                }
                else {
                    TargetedQuiz TQuiz = new TargetedQuiz();
                    jtxtQuizQuestion.setText(TQuiz.TargetedQuestions(false, null));
                }
            }
            //this is to 
            else {
                boolean correct;
                // does the on screen stuff 
                String Question = jtxtQuizQuestion.getText();
                String answer = (jtxtUserAnswer.getText());
                // need to get rid of any spaces that could be inputted
        
                if ("".equals(jtxtQuizQuestion.getText())){
                    JOptionPane.showMessageDialog(this, 
                            "Pick Random Or Targeted", "Try Again" ,JOptionPane.ERROR_MESSAGE);
            
                }
                else if ("".equals(answer)){
                    JOptionPane.showMessageDialog(this, 
                            "Please Enter An Answer", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                }
                else{
                    correct = quiz.CheckAnswer( answer,Question);
            
                    if ( correct == true) {            
                        jLabelMark.setText("Marked: Correct");
                    }
                    else {
                        jLabelMark.setText("Marked: Incorrect");
                        String QuizQuestion = jtxtQuizQuestion.getText();
                        QuizDetails.ListOfQuestionsWrong.add(QuizQuestion);
                    }
           
                    int count = QuizQuestions.count(false);
                    // -1 cause it displays the current questions ur on not hte one youve done
                    QuizDetails.questionsDone = count;
                    float stats = QuizQuestions.CountingQuizStats(count ,correct, false);
                    // updates the temp stored data of this quiz
                    QuizDetails.CurrentStats = stats;
                    jLabelStats.setText ("Stats: " + stats + "%");
            
                    int Student_id = Login.InfoOfUserForThisLoginSession.StudentId ;
                    /// get topicID
                    TargetedQuiz TQuiz = new TargetedQuiz();
                    int topicID = TQuiz.ReturnTopicID(Question);
                    /// adds one to the numofquestionsdoen in databse for specific topic
                    quiz.AddOneToNumOfQuestionsDone(topicID, Student_id);
                    quiz.updateStats(correct, topicID, Student_id);
                    lCorrectAnswer.setText("Correct Answer: "  + QuizDetails.RealAnswer );
                    jtxtUserAnswer.setText("");
                    //int num = Integer.valueOf(jLabelQuestion.getText());
                    //jLabelQuestion.setText("Question: " + ( num + 1 ));
                    jButtonSubmit.setText("Next");
                }
            
            }
            
        }
        
        
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jtxtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHomeActionPerformed
        StudentHome submitButton = new StudentHome();  
        submitButton.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHomeActionPerformed

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        targeted = false;
        RandomQuiz quiz = new RandomQuiz();
        jtxtQuizQuestion.setText(quiz.RandomQuiz());
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jButtonTargetedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTargetedActionPerformed
        targeted = true; 
        TargetedQuiz TQuiz = new TargetedQuiz();
        jtxtQuizQuestion.setText(TQuiz.TargetedQuestions(false, null));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTargetedActionPerformed

    private void jFinishQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishQuizActionPerformed
        QuizOutput NewScreen = new QuizOutput();  
        NewScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jFinishQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quizzes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jButtonRandom;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JRadioButton jButtonTargeted;
    private javax.swing.JButton jFinishQuiz;
    private javax.swing.JLabel jLabelMark;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelStats;
    private javax.swing.JPanel jPanelCorrrectOrWrong;
    private javax.swing.JLabel jQuizzesLabel;
    private javax.swing.JButton jtxtHome;
    private javax.swing.JTextField jtxtQuizQuestion;
    private javax.swing.JTextField jtxtUserAnswer;
    private javax.swing.JLabel lCorrectAnswer;
    // End of variables declaration//GEN-END:variables
}
