/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quizzes;

import StudentHome.StudentHome;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 4-EBULL
 */
public class QuizOutput extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizOutput.class.getName());

    /**
     * Creates new form QuizOutput
     */
    public QuizOutput() {
        initComponents();
        //gets temp stored values from Quizzes
        
        ArrayList<String> ListOfCorrectAnswers = Quizzes.QuizDetails.ListOfAnswers;
        ArrayList<String> ListOfQuestionsWrong = Quizzes.QuizDetails.ListOfQuestionsWrong;
        ArrayList<String> ListOfUserAnswers = Quizzes.QuizDetails.ListOfUserAnswers;
        Float OverallStats = Quizzes.QuizDetails.CurrentStats;
        int QuestionsDone = Quizzes.QuizDetails.questionsDone;
        

        // sets up the table on screen 
        DefaultTableModel QuizOutputTable = new DefaultTableModel();
        QuizOutputTable.addColumn("Question Wrong");
        QuizOutputTable.addColumn("Answer");
        QuizOutputTable.addColumn("Your Answer");
        QuizOutputTable.addColumn("Topic");
        for ( int i = 0; i < ListOfQuestionsWrong.size(); i++){
            // gets the topic for the Questions 
            String Question = ListOfQuestionsWrong.get(i);
            String Answer = ListOfCorrectAnswers.get(i);
            String UserAnswer = ListOfUserAnswers.get(i);
            
            QuizOutputClass output = new QuizOutputClass();
            String Topic = output.ReturnTopic(Question);
            QuizOutputTable.addRow(new Object [] {Question,Answer,UserAnswer,Topic }); 
            
        }
        
        jTableResults.setModel(QuizOutputTable);
        // sets labels for the output of quiz
        jScore.setText("Score : " + String.valueOf(OverallStats) + " %");
        
        // resets all the data after the test
        jNumOfQuestions.setText("Number Of Questions Done : " + QuestionsDone);
        Quizzes.QuizDetails.ListOfAnswers.clear();
        Quizzes.QuizDetails.ListOfQuestionsWrong.clear();
        Quizzes.QuizDetails.CurrentStats = null;
        Quizzes.QuizDetails.questionsDone = 0;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScore = new javax.swing.JLabel();
        jNumOfQuestions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        ToHomeScreen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Quiz Results");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 179, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jScore.setText("Score : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 46, 0, 52);
        getContentPane().add(jScore, gridBagConstraints);

        jNumOfQuestions.setText("Num Of Questions : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 46, 0, 0);
        getContentPane().add(jNumOfQuestions, gridBagConstraints);

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableResults.setEnabled(false);
        jScrollPane1.setViewportView(jTableResults);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 349;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 37, 45, 52);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        ToHomeScreen.setText("Home");
        ToHomeScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToHomeScreenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 6, 0, 52);
        getContentPane().add(ToHomeScreen, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToHomeScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToHomeScreenActionPerformed
        StudentHome submitButton = new StudentHome();  
        submitButton.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ToHomeScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuizOutput().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToHomeScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNumOfQuestions;
    private javax.swing.JLabel jScore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
