/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import StudentHome.StudentHome;
import SignUp.LoginOrSignUp;
import TeacherHome.TeacherHome;
/**
 *
 * @author elois
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    /**
     * Creates new form Login
     */
    public Login() {
        center();
    }

    private static String user;
    private static int UserClassID;
    private static int StudentId;
    private static int TeacherId;
    
    public static String userType() {
        return user;
    }


    
    
    /////////////////////////////////////////////////////////////////////////////////////////////////////
    ///FOR NOW SET  THIS TO ID = 1 BUT WHEN DO LOGIN GET CLASS ID FROM DATABASSE AND PUT IT IN HERE INSTEAD
    
    public static int classId(){
        UserClassID = 1;
        return UserClassID;
    }
    
    public static int StudentID() {
        StudentId = 1;
        return StudentId;
    }
    public static int TeacherID() {
        TeacherId =1;
        return TeacherId;
    }

    public void center() {
        initComponents(); 
        
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jtxtLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSubmit = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtUsername.setForeground(new java.awt.Color(255, 102, 204));
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 320, 40));

        jtxtPassword.setForeground(new java.awt.Color(255, 102, 204));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 320, 40));

        jtxtLogin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jtxtLogin.setText("Login");
        getContentPane().add(jtxtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 200, 70));

        jLabel2.setText("Username ( 5+ characters) ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 230, 30));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 170, 40));

        jtxtSubmit.setText("Submit");
        jtxtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 100, 20));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Student");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Teacher");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed
        String Username = jtxtUsername.getText();
        if (Username.length() < 5 ){
            jtxtUsername.setText("Username must be larger than 5 characters");
        }
        // compare database
        
    }//GEN-LAST:event_jtxtUsernameActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        jtxtPassword.getPassword();
        
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jtxtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubmitActionPerformed
        if ("Student".equals(user)) {
            StudentHome ToStudentScreen = new StudentHome();  
            ToStudentScreen.setVisible(true);
            this.dispose();
        }
        if ("Teacher".equals(user)) {
            TeacherHome ToTeacherScreen = new TeacherHome();  
            ToTeacherScreen.setVisible(true);
            this.dispose();// TODO add your handling code here:
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubmitActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        LoginOrSignUp BackScreen = new LoginOrSignUp();  
        BackScreen.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        user = "Student";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        user = "Teacher";        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jtxtLogin;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JButton jtxtSubmit;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}