/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import StudentHome.StudentHome;
import SignUp.LoginOrSignUp;
import TeacherHome.TeacherHome;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author elois
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public class InfoOfUserForThisLoginSession{
        public static String userType = "";
        public static int UserClassID = -1;
        public static int StudentId = -1;
        public static int TeacherId = -1;
    }

    public void center() {
        initComponents(); 
    }
    
    String user;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonBack = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jtxtLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(125, 10, 0, 0);
        getContentPane().add(jButtonBack, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Student");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 85, 0, 0);
        getContentPane().add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Teacher");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        getContentPane().add(jRadioButton2, gridBagConstraints);

        jtxtUsername.setForeground(new java.awt.Color(255, 102, 204));
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 85, 0, 82);
        getContentPane().add(jtxtUsername, gridBagConstraints);

        jtxtPassword.setForeground(new java.awt.Color(255, 102, 204));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 85, 0, 82);
        getContentPane().add(jtxtPassword, gridBagConstraints);

        jtxtLogin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jtxtLogin.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(75, 26, 0, 0);
        getContentPane().add(jtxtLogin, gridBagConstraints);

        jLabel2.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 85, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 85, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jtxtSubmit.setText("Submit");
        jtxtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 46, 66, 0);
        getContentPane().add(jtxtSubmit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        LoginOrSignUp BackScreen = new LoginOrSignUp();
        BackScreen.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        user = "Student";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        user = "Teacher";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed

    }//GEN-LAST:event_jtxtUsernameActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed

    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jtxtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubmitActionPerformed
        // getting all detail need to comapare data
        // resets the important data incase people log out then log back in as someone else.

        String usernameInputed = jtxtUsername.getText();
        char[] passwordEntered = jtxtPassword.getPassword();
        // need to convert to a strign cause thats what the hash thing needs
        String passwordString = new String(passwordEntered);
        String Passwordhash = BCrypt.hashpw(passwordString, BCrypt.gensalt());
        
        // empty the char[]
        Arrays.fill(passwordEntered, '\0');
        
        
        CheckLoginDetails check = new CheckLoginDetails();
        boolean CheckUsernameAndPassword = check.checkPassword(usernameInputed,user,Passwordhash);

        // || = or is syntax
        // could change to add two more if statments so they know if username or passwords is incorrect. security issie ??
        if ("".equals(user)) {
            JOptionPane.showMessageDialog(this, "Select Student or Teacher", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!CheckUsernameAndPassword){
            JOptionPane.showMessageDialog(this, "Username and Password do not match", "Try Again" ,JOptionPane.ERROR_MESSAGE);
            jtxtPassword.setText("");
        }
        else {
            InfoOfUserForThisLoginSession.userType = user;
            int UsernameId = check.ReturnUsernameID(usernameInputed,user);
            if ("Student".equals(user)) {
                InfoOfUserForThisLoginSession.StudentId = UsernameId;
                // check. etc is the method used to get the class id using the usernameid
                int classID = check.getClassIdStudent(UsernameId);
                InfoOfUserForThisLoginSession.UserClassID = classID;
                StudentHome ToStudentScreen = new StudentHome();
                ToStudentScreen.setVisible(true);
                this.dispose();
            }
            if ("Teacher".equals(user)) {
                InfoOfUserForThisLoginSession.TeacherId = UsernameId;
                int classID = check.getClassIdTeacher(UsernameId);
                InfoOfUserForThisLoginSession.UserClassID = classID;
                TeacherHome ToTeacherScreen = new TeacherHome();
                ToTeacherScreen.setVisible(true);
                this.dispose();
            }
        }        
    }//GEN-LAST:event_jtxtSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jtxtLogin;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JButton jtxtSubmit;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
