/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewAssignmentsScreen;
import StudentHome.StudentHome;
import javax.swing.table.DefaultTableModel;
import Login.Login;
import Quizzes.Quizzes;
/**
 *
 * @author 4-EBULL
 */
public class ViewAssignmentsScreen extends javax.swing.JFrame {

    /**
     * Creates new form ViewAssignmentsScreen
     */
    public ViewAssignmentsScreen() {
        initComponents();
    }
    
    public class InfoForAssignment{
        public static int Assignmentid;
        public static int Assignedid;
    }
    // auto set to assignments to do 
    static boolean completed = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtxtHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssignments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("View Assignments");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 40, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jtxtHome.setText("Home");
        jtxtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 163, 0, 0);
        getContentPane().add(jtxtHome, gridBagConstraints);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 163, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Completed");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 203, 0, 0);
        getContentPane().add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Uncompleted");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 231, 0, 0);
        getContentPane().add(jRadioButton2, gridBagConstraints);

        jTableAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAssignments.setEnabled(false);
        jTableAssignments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignmentWhenClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAssignments);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 905;
        gridBagConstraints.ipady = 382;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 15, 55, 30);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHomeActionPerformed
        StudentHome submitButton = new StudentHome();  
        submitButton.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //completed = true means that its the doen assignments
        // add into table   
        int studentid = Login.InfoOfUserForThisLoginSession.StudentId;
        DefaultTableModel AssignmentsTable = new DefaultTableModel();
        AssignmentsTable = GettingAssignmentsForTheTable.RowsInTable(studentid,completed);
        jTableAssignments.setModel(AssignmentsTable);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        completed = true;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        completed = false;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void AssignmentWhenClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentWhenClicked
        // uses mouse handler 
        // click select to do assignment
        
        /// TO DO. MAKE SO U CANT PULL WHEN COMPLETED
        
        if (( evt.getClickCount() == 2) && !completed) {
            // this gets the row youve clicked on
            /// ROW STARTS AT ZERO
            int IdRow = jTableAssignments.rowAtPoint(evt.getPoint());
            String assignedAndAssignmentInfoid = (String)jTableAssignments.getValueAt(IdRow, 0);
            int ResourceRow = jTableAssignments.rowAtPoint(evt.getPoint());
            
            // gets assingm3net id and assigned id 1
            String[] parts = assignedAndAssignmentInfoid.split("-");
            int AssignmentID = Integer.valueOf(parts[0]);
            int AssignedID = Integer.valueOf(parts[1]);
            InfoForAssignment.Assignmentid = AssignmentID;
            InfoForAssignment.Assignedid = AssignedID;

            if (!(jTableAssignments.getValueAt(ResourceRow, 2) == null)){
                // Do resource
                String Resource = (String)jTableAssignments.getValueAt(ResourceRow, 2);
                try {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(Resource));
                    // maybe add a panel thats like click if u have watched the video 
                    // sets the assignment to done then 
                }
                catch ( Exception e ){
                    // brings up neew temp screen
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid URL");
                } 
            }
            else {
                
                // get assignments info 
                // already have Assignmentid,Assignedid, StudentID
                // get the NumOfQuestionsLeftToDo
                int QuestionsLeftToDo = GettingAssignmentsForTheTable.questionsLeftToDo(AssignmentID,AssignedID);
                Quizzes.QuizDetails.QuestionsLeft = QuestionsLeftToDo;
                Quizzes.QuizDetails.Assignment = true;
                // sends to Quzzes screen
                Quizzes QuizButton = new Quizzes();
                QuizButton.setVisible(true);
                this.dispose(); 
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_AssignmentWhenClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAssignmentsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAssignmentsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAssignmentsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAssignmentsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAssignmentsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAssignments;
    private javax.swing.JButton jtxtHome;
    // End of variables declaration//GEN-END:variables
}
