/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TeacherSetResources;
import Login.Login;
import TeacherHome.TeacherHome;
import java.util.ArrayList;

/**
 *
 * @author 4-EBULL
 */
public class TeacherSetResources extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeacherSetResources.class.getName());

    /**
     * Creates new form TeacherSetResources
     */
    public TeacherSetResources() {
        initComponents();
        // jPickResourceType
        ArrayList<String> ListOfTopics = AssigningAResource.SetBox();
        for (int i = 0; i < ListOfTopics.size(); i ++ ){
            jPickResourceType.addItem(ListOfTopics.get(i));
        }
        
    }
    String Resource = null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPickResourceType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResourceList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jAssign = new javax.swing.JButton();
        jResourceNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBackButton = new javax.swing.JButton();
        jDueDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRetryInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Set Resources");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 3, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jPickResourceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        jPickResourceType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickResourceTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 89, 0, 0);
        getContentPane().add(jPickResourceType, gridBagConstraints);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 29, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jResourceList.setForeground(new java.awt.Color(0, 153, 255));
        jResourceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickedForURL(evt);
            }
        });
        jScrollPane1.setViewportView(jResourceList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 274;
        gridBagConstraints.ipady = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 89, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Resources: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 89, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jAssign.setText("Assign");
        jAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAssignActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 35, 52, 0);
        getContentPane().add(jAssign, gridBagConstraints);

        jResourceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResourceNumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 89, 0, 0);
        getContentPane().add(jResourceNum, gridBagConstraints);

        jLabel3.setText("Select Resource (  Select Number ) : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 89, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 28, 0, 27);
        getContentPane().add(jBackButton, gridBagConstraints);

        jDueDate.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 95, 0, 0);
        getContentPane().add(jDueDate, gridBagConstraints);

        jLabel4.setText("Due Date ( YYYY-MM-DD):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 77, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        getContentPane().add(jRetryInput, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //wanna use button to set the resource type to be the one from the slected box
        String ResourceType = jPickResourceType.getSelectedItem().toString();
        jResourceList.setModel(AssigningAResource.ResourceListToScreen(ResourceType));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPickResourceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickResourceTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPickResourceTypeActionPerformed
////////////////////////////////////////////////////////////////////
    //fix whatever ive messed up here probs the or could be an and by accidnet and like it just kinda froze/ crashed a little fix it 
    // or the scanner ?? bro idk 
    private void jAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAssignActionPerformed
        int resourceNum = Integer.valueOf(jResourceNum.getText());
        
        String TypeOfResource = jPickResourceType.getSelectedItem().toString();
        String Duedate = jDueDate.getText();
        int ClassId = Login.InfoOfUserForThisLoginSession.UserClassID ;
        AssigningAResource.SetResourceToClassOrStudent(TypeOfResource,resourceNum,ClassId,Duedate );
        jResourceNum.setText("");
        jDueDate.setText("");
        
        

        // make eaher type in due date
        // class id make it a global variable.
        // TODO add your handling code here:
    }//GEN-LAST:event_jAssignActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
    TeacherHome ToHome = new TeacherHome();
    ToHome.setVisible(true);
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jResourceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResourceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResourceNumActionPerformed

    private void MouseClickedForURL(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickedForURL
        // reused code from Resourrces Student screen. 
        // this is for double click 
        if ( evt.getClickCount() == 2) {
            // set it to null cause the later line was having an issue with it not being initalised 
            String url = null;
            
            // evt = the mouse event object 'click'
            int index = jResourceList.locationToIndex(evt.getPoint());
            // ive put this cause index returns -1 if not found
            if ( index !=-1) {
                // gets the rest of the url after https: cause i put a num infornt of it before hand 
                // cause i reused code from teacher.set resource
                url = jResourceList.getModel().getElementAt(index);
                url = url.substring(url.indexOf("http"));
            }

            try {
                java.awt.Desktop.getDesktop().browse(new java.net.URI(url));
            }
            catch ( Exception e ){
                // brings up neew temp screen
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid URL");
            } 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MouseClickedForURL

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeacherSetResources().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAssign;
    private javax.swing.JButton jBackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jDueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jPickResourceType;
    private javax.swing.JList<String> jResourceList;
    private javax.swing.JTextField jResourceNum;
    private javax.swing.JLabel jRetryInput;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
