/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Settings;

import Login.Login;
import SignUp.LoginOrSignUp;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author 4-EBULL
 */
public class ChangeUserInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName());

    /**
     * Creates new form ChangeUsername
     */
    public ChangeUserInfo() {
        initComponents();
        jOriginalPassword.setVisible(false);
        jPasswordField.setVisible(false);
        jConfirmPasswordField.setVisible(false);
        String WhatToChange = Settings.WhatToChange.WhatToChange ;
        if ("Username".equals(WhatToChange)){
            jChange.setText("Change Username");
        }
        else if ("Email".equals(WhatToChange)){
            jChange.setText("Change Email");
        }
        else if ("Delete Account".equals(WhatToChange)){
            jChange.setText("Delete Account");
        }
        else if ("Password".equals(WhatToChange)){
            jChange.setText("Change Password");
            jInstructions.setText("Enter old Password. Then type out the new one twice");
            jOriginalPassword.setVisible(true);
            jPasswordField.setVisible(true);
            jConfirmPasswordField.setVisible(true);
            jChangeUsername.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChange = new javax.swing.JLabel();
        jChangeUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jOriginalPassword = new javax.swing.JPasswordField();
        jConfirmPasswordField = new javax.swing.JPasswordField();
        jPasswordField = new javax.swing.JPasswordField();
        jInstructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jChange.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jChange.setText("Change");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jChange, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jChangeUsername)
                            .addComponent(jOriginalPassword)
                            .addComponent(jConfirmPasswordField)
                            .addComponent(jPasswordField)
                            .addComponent(jInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChange)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addComponent(jInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChangeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jOriginalPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(551, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int StudentId = Login.InfoOfUserForThisLoginSession.StudentId;
        int TeacherID = Login.InfoOfUserForThisLoginSession.TeacherId;
        String userType = Login.InfoOfUserForThisLoginSession.userType ;
        int id;
        if ("Student".equals(userType)){
            id = StudentId;
        }
        else {
            id = TeacherID;
        }
        
        GetOrChangeUserInfo change = new GetOrChangeUserInfo();
        
        String WhatToChange = Settings.WhatToChange.WhatToChange ;
        String UserInput = jChangeUsername.getText();
        if ("Username".equals(WhatToChange)){
            
            boolean success = change.ChangeUsername(userType,UserInput, id );
            if (success){
                JOptionPane.showMessageDialog(this, "Change Successful.", 
                        "Username Updated" ,JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Change Unsuccessful. Enter a unique username", 
                        "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
        }
        else if ("Email".equals(WhatToChange)){
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirm this is your new email :" + UserInput,
                            "Confirm" ,JOptionPane.YES_NO_OPTION)){
                boolean Success = change.ChangeEmail(userType, UserInput, id);
                if (Success){
                    JOptionPane.showMessageDialog(this, "Change Successful.", 
                        "Email Updated" ,JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Change Unsuccessful. Email must not already have an account", 
                        "Try Again" ,JOptionPane.ERROR_MESSAGE);
                }
                jChangeUsername.setText("");
            }
        }
        else if ("Delete Account".equals(WhatToChange)){

            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Are You Sure You Would Like To Delete Your Account",
                        "Confirm" ,JOptionPane.YES_NO_OPTION)){
                boolean success = change.DeleteAccount(id, userType);
                if (success) {
                    LoginOrSignUp BackScreen = new LoginOrSignUp();
                    BackScreen.setVisible(true);
                    this.dispose();  
                }
                else {
                    JOptionPane.showConfirmDialog(this, "Account Wasn't Deleted","Try Again" ,JOptionPane.ERROR_MESSAGE);
                }
            }
        }
            
        else if ("Password".equals(WhatToChange)) {
            char[] OriginalPassword = jOriginalPassword.getPassword();
            char[] Password = jPasswordField.getPassword();
            char[] CheckPassword = jConfirmPasswordField.getPassword();

            String passwordString = new String(Password);
            String Passwordhash = BCrypt.hashpw(passwordString, BCrypt.gensalt());
            
            String OriginalpasswordString = new String(OriginalPassword);
            
            int passwordLength = Password.length;
            int ConfirmpasswordLength = CheckPassword.length;
            boolean SamePassword = false;
            if (Arrays.equals(Password,CheckPassword)){
                SamePassword = true;
            }
            // empty the char[]
            Arrays.fill(Password, '\0');
            Arrays.fill(CheckPassword, '\0');
            Arrays.fill(OriginalPassword, '\0');
            // check original password = the one in database
            GetOrChangeUserInfo changeInfo = new GetOrChangeUserInfo();
            // EnteredPassword,PasswordHash
            boolean correctOldPassword = changeInfo.checkPasswordToOldOne(userType, id, OriginalpasswordString);
            if (!correctOldPassword){
                JOptionPane.showMessageDialog(this, "Change Unsuccessful. The Original Password is incorrect", 
                            "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
            else if ((passwordLength==0) || (ConfirmpasswordLength==0)){
                JOptionPane.showMessageDialog(this, "Change Unsuccessful. Password fields cant be empty", 
                            "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
            else if (!SamePassword) {
                JOptionPane.showMessageDialog(this, "Passwords don't match", "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
            else if (passwordLength < 6){
                JOptionPane.showMessageDialog(this, "Password must be more than 6 characters", "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
            else {
                // can change password.
                changeInfo.ChangePassword(userType,Passwordhash, id);
                JOptionPane.showMessageDialog(this, "Password Changed", "Success" ,JOptionPane.INFORMATION_MESSAGE);
                
            }
        }  
        else if ("Delete Account".equals(WhatToChange)){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Settings viewSettings = new Settings();
        viewSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangeUserInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jChange;
    private javax.swing.JTextField jChangeUsername;
    private javax.swing.JPasswordField jConfirmPasswordField;
    private javax.swing.JLabel jInstructions;
    private javax.swing.JPasswordField jOriginalPassword;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
