/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Settings;

import Login.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author 4-EBULL
 */
public class ChangeUserInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName());

    /**
     * Creates new form ChangeUsername
     */
    public ChangeUserInfo() {
        initComponents();
        String WhatToChange = Settings.WhatToChange.WhatToChange ;
        if ("Username".equals(WhatToChange)){
            jChange.setText("Change Username");
        }
        else if ("Email".equals(WhatToChange)){
            jChange.setText("Change Email");
        }
        else if ("Class".equals(WhatToChange)){
            jChange.setText("Change Class");
        }
        if ("Password".equals(WhatToChange)){
            jChange.setText("Change Password");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChange = new javax.swing.JLabel();
        jChangeUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jChange.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jChange.setText("Change");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jChangeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jChange)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jChange)
                .addGap(43, 43, 43)
                .addComponent(jChangeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2))
        );

        setSize(new java.awt.Dimension(551, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int StudentId = Login.InfoOfUserForThisLoginSession.StudentId;
        int TeacherID = Login.InfoOfUserForThisLoginSession.TeacherId;
        String userType = Login.InfoOfUserForThisLoginSession.userType ;
        int id;
        if ("Student".equals(userType)){
            id = StudentId;
        }
        else {
            id = TeacherID;
        }
        
        GetOrChangeUserInfo change = new GetOrChangeUserInfo();
        
        String WhatToChange = Settings.WhatToChange.WhatToChange ;
        String UserInput = jChangeUsername.getText();
        if ("Username".equals(WhatToChange)){
            
            boolean success = change.ChangeUsername(userType,UserInput, id );
            if (success){
                JOptionPane.showMessageDialog(this, "Change Successful.", 
                        "Username Updated" ,JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Change Unsuccessful. Enter a unique username", 
                        "Try Again" ,JOptionPane.ERROR_MESSAGE);
            }
        }
        else if ("Email".equals(WhatToChange)){
            System.out.println("OPTION");
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirm this is your new email :" + UserInput,
                            "Confirm" ,JOptionPane.YES_NO_OPTION)){
                System.out.println("AFTER OPTION");
                boolean Success = change.ChangeEmail(userType, UserInput, id);
                System.out.println(Success);
                if (Success){
                    JOptionPane.showMessageDialog(this, "Change Successful.", 
                        "Email Updated" ,JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Change Unsuccessful. Email must not already have an account", 
                        "Try Again" ,JOptionPane.ERROR_MESSAGE);
                }
                jChangeUsername.setText("");
            }
            
                        
        }    
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Settings viewSettings = new Settings();
        viewSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangeUserInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jChange;
    private javax.swing.JTextField jChangeUsername;
    // End of variables declaration//GEN-END:variables
}
