/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Settings;

import Login.Login;
import StudentHome.StudentHome;
import TeacherHome.TeacherHome;


/**
 *
 * @author 4-EBULL
 */
public class Settings extends javax.swing.JFrame {
    /**
     * Creates new form Settings
     */
    public class WhatToChange{
        public static String WhatToChange;
    }
    
    
    public Settings() {
        initComponents();
        int ClassID = Login.InfoOfUserForThisLoginSession.UserClassID;
        int StudentId = Login.InfoOfUserForThisLoginSession.StudentId;
        int TeacherID = Login.InfoOfUserForThisLoginSession.TeacherId;
        String userType = Login.InfoOfUserForThisLoginSession.userType ;
        String[] DataArray = new String[3];
        GetOrChangeUserInfo get = new GetOrChangeUserInfo();
        DataArray = get.GetUserInfo(ClassID,userType,StudentId,TeacherID);
        jtxtUsername.setText("Username : " + DataArray[0]);
        jtxtEmail.setText("Email : " + DataArray[1]);
        jtxtClass.setText("Class : " + ClassID );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtClass = new javax.swing.JTextField();
        jChangePassword = new javax.swing.JButton();
        jChangeUsername = new javax.swing.JButton();
        jChangeClass = new javax.swing.JButton();
        jChangeEmail = new javax.swing.JButton();
        jtxtHome = new javax.swing.JButton();

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Settings");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 135, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jtxtUsername.setEditable(false);
        jtxtUsername.setText("Username : ");
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 23, 0, 0);
        getContentPane().add(jtxtUsername, gridBagConstraints);

        jtxtPassword.setEditable(false);
        jtxtPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(jtxtPassword, gridBagConstraints);

        jtxtEmail.setEditable(false);
        jtxtEmail.setText("Email : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        getContentPane().add(jtxtEmail, gridBagConstraints);

        jtxtClass.setEditable(false);
        jtxtClass.setText("Class : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 102, 0);
        getContentPane().add(jtxtClass, gridBagConstraints);

        jChangePassword.setText("Change");
        jChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 0, 43);
        getContentPane().add(jChangePassword, gridBagConstraints);

        jChangeUsername.setText("Change");
        jChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 12, 0, 43);
        getContentPane().add(jChangeUsername, gridBagConstraints);

        jChangeClass.setText("Change");
        jChangeClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeClassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 0, 43);
        getContentPane().add(jChangeClass, gridBagConstraints);

        jChangeEmail.setText("Change");
        jChangeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 0, 43);
        getContentPane().add(jChangeEmail, gridBagConstraints);

        jtxtHome.setText("Home");
        jtxtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 12, 0, 43);
        getContentPane().add(jtxtHome, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed

    }//GEN-LAST:event_jtxtUsernameActionPerformed

    private void jChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeUsernameActionPerformed
        WhatToChange.WhatToChange = "Username";
        ChangeUserInfo ToNextScreen = new ChangeUserInfo();  
        ToNextScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jChangeUsernameActionPerformed

    private void jtxtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHomeActionPerformed
        String User = Login.InfoOfUserForThisLoginSession.userType ;
        if (User.equals("Teacher")){
            TeacherHome ToTeacherScreen = new TeacherHome();  
            ToTeacherScreen.setVisible(true);
            this.dispose();
        }
        if (User.equals("Student")){
            StudentHome submitButton = new StudentHome();  
            submitButton.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_jtxtHomeActionPerformed

    private void jChangeClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeClassActionPerformed
        WhatToChange.WhatToChange = "Class";

        String User = Login.InfoOfUserForThisLoginSession.userType ;
        if (User.equals("Teacher")){
            TeacherRemovePeople ToNewScreen = new TeacherRemovePeople();  
            ToNewScreen.setVisible(true);
            this.dispose();
        }
        else{
            ChangeUserInfo ToNextScreen = new ChangeUserInfo();  
            ToNextScreen.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_jChangeClassActionPerformed

    private void jChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangePasswordActionPerformed
        WhatToChange.WhatToChange = "Password";
        ChangeUserInfo ToNextScreen = new ChangeUserInfo();  
        ToNextScreen.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jChangePasswordActionPerformed

    private void jChangeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeEmailActionPerformed
        WhatToChange.WhatToChange = "Email";
        ChangeUserInfo ToNextScreen = new ChangeUserInfo();  
        ToNextScreen.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jChangeEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChangeClass;
    private javax.swing.JButton jChangeEmail;
    private javax.swing.JButton jChangePassword;
    private javax.swing.JButton jChangeUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jtxtClass;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JButton jtxtHome;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
