/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentHome;
import Quizzes.Quizzes;
import Login.Login;
import Settings.Settings;
import Resources.Resources;
import StudentStatsScreen.StudentStatsScreen;
import ViewAssignmentsScreen.ViewAssignmentsScreen;
/**
 *
 * @author 4-EBULL
 */
public class StudentHome extends javax.swing.JFrame {

    /**
     * Creates new form StudentHome
     */
    public StudentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /// buttons send user to next screen 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbuttonQuiz = new javax.swing.JButton();
        jbuttonResources = new javax.swing.JButton();
        jbuttonAssignments = new javax.swing.JButton();
        jbuttonStats = new javax.swing.JButton();
        jbuttonSettings = new javax.swing.JButton();
        jbuttonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Student Menu");

        jbuttonQuiz.setText("QUIZ");
        jbuttonQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonQuizActionPerformed(evt);
            }
        });

        jbuttonResources.setText("RESOURCES");
        jbuttonResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResourcesActionPerformed(evt);
            }
        });

        jbuttonAssignments.setText("ASSIGNMENTS");
        jbuttonAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAssignmentsActionPerformed(evt);
            }
        });

        jbuttonStats.setText("STATISTICS");
        jbuttonStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonStatsActionPerformed(evt);
            }
        });

        jbuttonSettings.setText("SETTINGS");
        jbuttonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSettingsActionPerformed(evt);
            }
        });

        jbuttonLogOut.setText("Log Out");
        jbuttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(jbuttonLogOut))
                    .addComponent(jbuttonSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuttonStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuttonAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(jbuttonResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuttonQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addComponent(jbuttonLogOut))
                .addGap(18, 18, 18)
                .addComponent(jbuttonQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonResources, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonStats, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonQuizActionPerformed
        Quizzes.QuizDetails.Assignment = false;
        
        Quizzes QuizButton = new Quizzes();
        QuizButton.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbuttonQuizActionPerformed

    private void jbuttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonLogOutActionPerformed
        Login logout = new Login();
        logout.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jbuttonLogOutActionPerformed

    private void jbuttonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSettingsActionPerformed
        Settings viewSettings = new Settings();
        viewSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbuttonSettingsActionPerformed

    private void jbuttonResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResourcesActionPerformed
        Resources viewResources = new Resources();
        viewResources.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonResourcesActionPerformed

    private void jbuttonStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonStatsActionPerformed
        StudentStatsScreen ViewStudentStatsScreen = new StudentStatsScreen();
        ViewStudentStatsScreen.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonStatsActionPerformed

    private void jbuttonAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAssignmentsActionPerformed
        ViewAssignmentsScreen ViewAssignments = new ViewAssignmentsScreen();
        ViewAssignments.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonAssignmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbuttonAssignments;
    private javax.swing.JButton jbuttonLogOut;
    private javax.swing.JButton jbuttonQuiz;
    private javax.swing.JButton jbuttonResources;
    private javax.swing.JButton jbuttonSettings;
    private javax.swing.JButton jbuttonStats;
    // End of variables declaration//GEN-END:variables
}
