/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TeacherSeeSetAssignment;
import Login.Login;
import Settings.ChangeUserInfo;
import TeacherHome.TeacherHome;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 4-EBULL
 */
public class TeacherSeeSetAssignments extends javax.swing.JFrame {

    /**
     * Creates new form TeacherSetAssignment
     */
    public TeacherSeeSetAssignments() {
        initComponents();
        int ClassID = Login.InfoOfUserForThisLoginSession.UserClassID;
        ArrayList<String> ListOfUsernames = SeeSetAssignmentsFromDatabase.SetBox(ClassID);
        for (int i = 0; i < ListOfUsernames.size(); i ++ ){
            ComboBox.addItem(ListOfUsernames.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAssignmentsTable = new javax.swing.JTable();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 26);
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Assignments");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 116, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jAssignmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jAssignmentsTable.setEnabled(false);
        jAssignmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeAssignmentOrGoResource(evt);
            }
        });
        jScrollPane2.setViewportView(jAssignmentsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 314;
        gridBagConstraints.ipady = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 26, 50, 26);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DueNext", "Uncompleted", "Completed", "All" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(ComboBox, gridBagConstraints);

        jLabel2.setText("Sort Assignments: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 26, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jButton4.setText("Choose");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 151, 0, 26);
        getContentPane().add(jButton4, gridBagConstraints);

        jLabel3.setText("Double click an assignment to change it, or access a resource.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 26);
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    TeacherHome ToHome = new TeacherHome();
    ToHome.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String HowToSort = ComboBox.getSelectedItem().toString();
        int ClassID = Login.InfoOfUserForThisLoginSession.UserClassID;
        System.out.println(HowToSort);
        if ("DueNext".equals(HowToSort)){
             // sort by date and then limit one 
            
            DefaultTableModel AssignmentsTable = new DefaultTableModel();
            AssignmentsTable = SeeSetAssignmentsFromDatabase.DueNext(ClassID);
            jAssignmentsTable.setModel(AssignmentsTable);
            
           
        }    
        else if ("Uncompleted".equals(HowToSort)|| "Completed".equals(HowToSort)){
            // this fills in the table
            DefaultTableModel AssignmentsTable = new DefaultTableModel();
            AssignmentsTable = SeeSetAssignmentsFromDatabase.BothCompletedAndUncompletedAssignmentsTable(ClassID, HowToSort);
            jAssignmentsTable.setModel(AssignmentsTable);
        }
        else if ("All".equals(HowToSort)){
            
            DefaultTableModel AssignmentsTable = new DefaultTableModel();
            AssignmentsTable = SeeSetAssignmentsFromDatabase.AllAssignments(ClassID);
            jAssignmentsTable.setModel(AssignmentsTable);
        }
        else{
            DefaultTableModel AssignmentsTable = new DefaultTableModel();
            // in this context howToSort is the Student USerrname 
            AssignmentsTable = SeeSetAssignmentsFromDatabase.SpecificStudentAssignment(HowToSort, ClassID);
            jAssignmentsTable.setModel(AssignmentsTable);
        }

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ChangeAssignmentOrGoResource(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeAssignmentOrGoResource
        
        if (( evt.getClickCount() == 2)) {
            // this gets the row youve clicked on
            /// ROW STARTS AT ZERO
            int IdRow = jAssignmentsTable.rowAtPoint(evt.getPoint());
            String assignedAndAssignmentInfoid = (String)jAssignmentsTable.getValueAt(IdRow, 0);
            int ResourceRow = jAssignmentsTable.rowAtPoint(evt.getPoint());
            
            // gets assingm3net id and assigned id 1
            String[] parts = assignedAndAssignmentInfoid.split("-");
            int AssignmentID = Integer.parseInt(parts[0]);
            int AssignedID = Integer.parseInt(parts[1]);

            
            
            if ((jAssignmentsTable.getValueAt(ResourceRow, 4) == null)){
                // no resource
                String[] Options = new String[2];
                Options[0] = "Extend Deadline";
                Options[1] = "Delete Assignment";
                int choice = JOptionPane.showOptionDialog(null, "What would you like to do ?","",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null,Options,Options[1]);
                // choice 0 is extend deadline
                if(choice == 0){
                    String Extend = JOptionPane.showInputDialog("By how many days would you like to extend it? Only Type Numbers");
                    int ExtendDays = Integer.parseInt(Extend);
                    boolean Success = SeeSetAssignmentsFromDatabase.UpdateDateForAssignment(ExtendDays, AssignmentID);
                    if (Success) {
                        JOptionPane.showMessageDialog(this, "Deadline extended by " + ExtendDays + " days", "Success" ,JOptionPane.INFORMATION_MESSAGE);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Failed", "" ,JOptionPane.ERROR_MESSAGE);
                    }
                }
                else if ( choice == 1){
                    JOptionPane.showMessageDialog(this, "Are you sure you'd like to delete this assignment for eveyone ?",
                            "Confirm" ,JOptionPane.YES_NO_OPTION);
                    if (JOptionPane.YES_OPTION ==1){
                        boolean Success = SeeSetAssignmentsFromDatabase.DeleteAssignment(AssignmentID);
                        if (Success) {
                            JOptionPane.showMessageDialog(this, "Assignment deleted", "Success" ,JOptionPane.INFORMATION_MESSAGE);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Failed", "" ,JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    
                        
                }
            }
            // ive put this as an else as if there is an assignmetn then they can access the resource
            else {
                String[] Options = new String[3];
                Options[0] = "Access Resource";
                Options[1] = "Extend Deadline";
                Options[2] = "Delete Assignment";
                
                int choice = JOptionPane.showOptionDialog(null, "What would you like to do ?","",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null,Options,Options[1]);
                
                if(choice == 0){
                    // access resource
                    System.out.println("1");
                    String Resource = (String)jAssignmentsTable.getValueAt(ResourceRow, 4);
                    try {
                        java.awt.Desktop.getDesktop().browse(new java.net.URI(Resource));
                        // maybe add a panel thats like click if u have watched the video 
                        // sets the assignment to done then 
                    }
                    catch ( Exception e ){
                        // brings up neew temp screen
                        javax.swing.JOptionPane.showMessageDialog(this, "Invalid URL");
                    } 
                }
                else if ( choice == 1 ){
                    // extend deadline
                    String Extend = JOptionPane.showInputDialog("By how many days would you like to extend it? Only Type Numbers");
                    int ExtendDays = Integer.parseInt(Extend);
                    boolean Success = SeeSetAssignmentsFromDatabase.UpdateDateForAssignment(ExtendDays, AssignmentID);
                    if (Success) {
                        JOptionPane.showMessageDialog(this, "Deadline extended by " + ExtendDays + " days", "Success" ,JOptionPane.INFORMATION_MESSAGE);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Failed", "" ,JOptionPane.ERROR_MESSAGE);
                    }
                }
                else if (choice == 2){
                    JOptionPane.showMessageDialog(this, "Are you sure you'd like to delete this assignment for eveyone ?",
                            "Confirm" ,JOptionPane.YES_NO_OPTION);
                    if (JOptionPane.YES_OPTION ==1){
                        boolean Success = SeeSetAssignmentsFromDatabase.DeleteAssignment(AssignmentID);
                        if (Success) {
                            JOptionPane.showMessageDialog(this, "Assignment deleted", "Success" ,JOptionPane.INFORMATION_MESSAGE);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Failed", "" ,JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    
                }
                
            }
        } 
        
    }//GEN-LAST:event_ChangeAssignmentOrGoResource

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSeeSetAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSeeSetAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSeeSetAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSeeSetAssignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherSeeSetAssignments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTable jAssignmentsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
