/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignUp;
import Login.Login;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author 4-EBULL
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    private static String user;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jRadioStudent = new javax.swing.JRadioButton();
        jRadioTeacher = new javax.swing.JRadioButton();
        jtxtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jbuttonSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTellUserInfo = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLClassCode = new javax.swing.JLabel();
        jtxtClassCode = new javax.swing.JTextField();
        jtxtSchool = new javax.swing.JTextField();
        jLSchool = new javax.swing.JLabel();
        jgetPassword = new javax.swing.JPasswordField();
        jConfirmPassword = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioStudent);
        jRadioStudent.setText("Student");
        jRadioStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioStudentActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioTeacher);
        jRadioTeacher.setText("Teacher");
        jRadioTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTeacherActionPerformed(evt);
            }
        });

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username :");

        jLabel4.setText("Password :");

        jLabel5.setText("Check Password :");

        jLabel6.setText("Email :");

        jbuttonSubmit.setText("Submit");
        jbuttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSubmitActionPerformed(evt);
            }
        });

        jLabelUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel8.setText("Name :");

        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });

        jLClassCode.setText("Class Code:");

        jLSchool.setText("School :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabel7)
                    .addComponent(JTellUserInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(jButtonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jRadioStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jRadioTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel8)
                        .addGap(120, 120, 120)
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLSchool)
                        .addGap(116, 116, 116)
                        .addComponent(jtxtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLClassCode)
                        .addGap(98, 98, 98)
                        .addComponent(jtxtClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jbuttonSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUsername)
                            .addComponent(jgetPassword)
                            .addComponent(jConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabel7)
                    .addComponent(JTellUserInfo))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBack))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioStudent)
                    .addComponent(jRadioTeacher))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jgetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLSchool))
                    .addComponent(jtxtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLClassCode))
                    .addComponent(jtxtClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jbuttonSubmit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    LoginOrSignUp ToFirstScreen = new LoginOrSignUp();  
    ToFirstScreen.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jRadioStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioStudentActionPerformed
        user = "Student";    
        jLClassCode.setVisible(true);
        jtxtClassCode.setVisible(true);
        jLSchool.setVisible(false);
        jtxtSchool.setVisible(false);
    }//GEN-LAST:event_jRadioStudentActionPerformed

    private void jRadioTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTeacherActionPerformed
        user = "Teacher";  
        jLClassCode.setVisible(false);
        jtxtClassCode.setVisible(false);
        jLSchool.setVisible(true);
        jtxtSchool.setVisible(true);
    }//GEN-LAST:event_jRadioTeacherActionPerformed

    private void jbuttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSubmitActionPerformed
        String name = jtxtName.getText();
        String Username = jtxtUsername.getText();
        String Email = jtxtEmail.getText();
        String Classcode = jtxtClassCode.getText();
        String School = jtxtSchool.getText();
        // change later so its better
        char[] Password = jgetPassword.getPassword();
        char[] CheckPassword = jConfirmPassword.getPassword();
        // i used this in the else if statement to check if username = unique
        checkSignUp check = new checkSignUp();
        
        String passwordString = new String(Password);
        String Passwordhash = BCrypt.hashpw(passwordString, BCrypt.gensalt());
        
        int passwordLength = Password.length;
        int ConfirmpasswordLength = CheckPassword.length;
        boolean SamePassword = false;
        if (Arrays.equals(Password,CheckPassword)){
            SamePassword = true;
        }
        // empty the char[]
        Arrays.fill(Password, '\0');
        Arrays.fill(CheckPassword, '\0');
        
        // need to check classcode is an integer before i make it one
        // need to use try / catch 
        // cant have it between ifs
        boolean CanBeInteger;
        try {
            int value = Integer.parseInt(Classcode);
            CanBeInteger = true;
        }
        catch (NumberFormatException e){
            CanBeInteger = false;
        }
        
        
        // checks all nesassary boxes are filled out
        if ((name.length()==0) || (Username.length()==0) || (Email.length()==0)||(passwordLength==0) || (ConfirmpasswordLength==0)){
            JOptionPane.showMessageDialog(this, "All fields must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!SamePassword) {
            JOptionPane.showMessageDialog(this, "Passwords don't match", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (passwordLength < 6){
            JOptionPane.showMessageDialog(this, "Password must be more than 6 characters", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        // check username is unique to the user table
        // check username is unique - not used as the primary key or anything just to distinquish 
        else if (!(check.UsernameUniquenessCheck(user,Username ))){
            JOptionPane.showMessageDialog(this, "Please username must be unique", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (("Student".equals(user)) && (Classcode.length()==0)){
            JOptionPane.showMessageDialog(this, "Classcode must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!CanBeInteger){
            JOptionPane.showMessageDialog(this, "Classcode must be a number", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        // checks that the classcode actually exsits
        else if (("Student".equals(user)) && !(check.CheckClassCodeExists(Integer.parseInt(Classcode)))) {
            JOptionPane.showMessageDialog(this, "Classcode does not exist", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if ("Teacher".equals(user) && (School.length()==0)){
            JOptionPane.showMessageDialog(this, "School must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        } 
        else if ( user == null) {
            JOptionPane.showMessageDialog(this, "Pick Teacher or Student", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (Username.length()>20){
            JOptionPane.showMessageDialog(this, "Username must be less than 20 characters", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        } 
        else {
            if ( "Student".equals(user)){
                Boolean worked = check.AddStudent(name, Username, Email, Passwordhash, Integer.parseInt(Classcode));
                if (worked){
                    Login ToLoginScreen = new Login();  
                    ToLoginScreen.setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(this, "There has been an issue please retry", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                    jtxtName.setText("");
                    jtxtUsername.setText("");
                    jtxtEmail.setText("");
                    jtxtClassCode.setText("");
                    jtxtSchool.setText("");
                    jgetPassword.setText("");
                    jConfirmPassword.setText("");
                }
            }
            if ( "Teacher".equals(user)){
                check.AddTeacher(name, Username, Email,  Passwordhash, School);
                Login ToLoginScreen = new Login();  
                ToLoginScreen.setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "There has been an issue please retry", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                jtxtName.setText("");
                jtxtUsername.setText("");
                jtxtEmail.setText("");
                jtxtClassCode.setText("");
                jtxtSchool.setText("");
                jgetPassword.setText("");
                jConfirmPassword.setText("");
            }
        }
    }//GEN-LAST:event_jbuttonSubmitActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed

    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed

    }//GEN-LAST:event_jtxtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTellUserInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JLabel jLClassCode;
    private javax.swing.JLabel jLSchool;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JRadioButton jRadioStudent;
    private javax.swing.JRadioButton jRadioTeacher;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbuttonSubmit;
    private javax.swing.JPasswordField jgetPassword;
    private javax.swing.JTextField jtxtClassCode;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSchool;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
