/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SignUp;
import Login.Login;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author 4-EBULL
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    private static String user;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jRadioStudent = new javax.swing.JRadioButton();
        jRadioTeacher = new javax.swing.JRadioButton();
        jtxtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jbuttonSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTellUserInfo = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLClassCode = new javax.swing.JLabel();
        jtxtClassCode = new javax.swing.JTextField();
        jtxtSchool = new javax.swing.JTextField();
        jLSchool = new javax.swing.JLabel();
        jgetPassword = new javax.swing.JPasswordField();
        jConfirmPassword = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 4, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 45;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 87, 0, 49);
        getContentPane().add(jButtonBack, gridBagConstraints);

        buttonGroup1.add(jRadioStudent);
        jRadioStudent.setText("Student");
        jRadioStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioStudentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 84, 0, 0);
        getContentPane().add(jRadioStudent, gridBagConstraints);

        buttonGroup1.add(jRadioTeacher);
        jRadioTeacher.setText("Teacher");
        jRadioTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTeacherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 45;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 59, 0, 0);
        getContentPane().add(jRadioTeacher, gridBagConstraints);

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 46, 0, 0);
        getContentPane().add(jtxtName, gridBagConstraints);

        jLabel2.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 84, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel4.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 84, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Check Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 84, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Email :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 84, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 46, 0, 0);
        getContentPane().add(jtxtEmail, gridBagConstraints);

        jbuttonSubmit.setText("Submit");
        jbuttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 12, 62, 0);
        getContentPane().add(jbuttonSubmit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(JTellUserInfo, gridBagConstraints);

        jLabelUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabelUsername, gridBagConstraints);

        jLabel8.setText("Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 84, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 46, 0, 0);
        getContentPane().add(jtxtUsername, gridBagConstraints);

        jLClassCode.setText("Class Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 84, 0, 0);
        getContentPane().add(jLClassCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 51;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 47, 0, 0);
        getContentPane().add(jtxtClassCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 46, 0, 0);
        getContentPane().add(jtxtSchool, gridBagConstraints);

        jLSchool.setText("School :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 84, 0, 0);
        getContentPane().add(jLSchool, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 0, 0);
        getContentPane().add(jgetPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 46, 0, 0);
        getContentPane().add(jConfirmPassword, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        LoginOrSignUp ToFirstScreen = new LoginOrSignUp();  
        ToFirstScreen.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jRadioStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioStudentActionPerformed
        user = "Student";    
        jLClassCode.setVisible(true);
        jtxtClassCode.setVisible(true);
        jLSchool.setVisible(false);
        jtxtSchool.setVisible(false);
    }//GEN-LAST:event_jRadioStudentActionPerformed

    private void jRadioTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTeacherActionPerformed
        user = "Teacher";  
        jLClassCode.setVisible(false);
        jtxtClassCode.setVisible(false);
        jLSchool.setVisible(true);
        jtxtSchool.setVisible(true);
    }//GEN-LAST:event_jRadioTeacherActionPerformed

    private void jbuttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSubmitActionPerformed
        String name = jtxtName.getText();
        String Username = jtxtUsername.getText();
        String Email = jtxtEmail.getText();
        String Classcode = jtxtClassCode.getText();
        String School = jtxtSchool.getText();
        // change later so its better
        char[] Password = jgetPassword.getPassword();
        char[] CheckPassword = jConfirmPassword.getPassword();
        // i used this in the else if statement to check if username = unique
        checkSignUp check = new checkSignUp();
        
        String passwordString = new String(Password);
        String Passwordhash = BCrypt.hashpw(passwordString, BCrypt.gensalt());
        
        int passwordLength = Password.length;
        int ConfirmpasswordLength = CheckPassword.length;
        boolean SamePassword = false;
        if (Arrays.equals(Password,CheckPassword)){
            SamePassword = true;
        }
        // empty the char[]
        Arrays.fill(Password, '\0');
        Arrays.fill(CheckPassword, '\0');
        
        // need to check classcode is an integer before i make it one
        // need to use try / catch 
        // cant have it between ifs
        boolean CanBeInteger;
        try {
            Integer.valueOf(Classcode);
            CanBeInteger = true;
        }
        catch (NumberFormatException e){
            CanBeInteger = false;
        }
        
        
        // checks all nesassary boxes are filled out
        if ((name.length()==0) || (Username.length()==0) || (Email.length()==0)||(passwordLength==0) || (ConfirmpasswordLength==0)){
            JOptionPane.showMessageDialog(this, "All fields must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if ( "".equals(user)) {
            JOptionPane.showMessageDialog(this, "Pick Teacher or Student", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!SamePassword) {
            JOptionPane.showMessageDialog(this, "Passwords don't match", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (passwordLength < 6){
            JOptionPane.showMessageDialog(this, "Password must be more than 6 characters", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        // check username is unique to the user table
        // check username is unique - not used as the primary key or anything just to distinquish 
        else if (!(check.UsernameUniquenessCheck(user,Username ))){
            JOptionPane.showMessageDialog(this, "Please username must be unique", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!(check.EmailUniquenessCheck(user,Email ))){
            JOptionPane.showMessageDialog(this, "This Email already has an account", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (("Student".equals(user)) && (Classcode.length()==0)){
            JOptionPane.showMessageDialog(this, "Classcode must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if (!CanBeInteger &&("Student".equals(user))){
            JOptionPane.showMessageDialog(this, "Classcode must be a number", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        // checks that the classcode actually exsits
        else if (("Student".equals(user)) && !(check.CheckClassCodeExists(Integer.parseInt(Classcode)))) {
            JOptionPane.showMessageDialog(this, "Classcode does not exist", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        }
        else if ("Teacher".equals(user) && (School.length()==0)){
            JOptionPane.showMessageDialog(this, "School must be filled", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        } 
        else if (Username.length()>20){
            JOptionPane.showMessageDialog(this, "Username must be less than 20 characters", "Try Again" ,JOptionPane.ERROR_MESSAGE);
        } 
        else {
            if ( "Student".equals(user)){
                Boolean worked = check.AddStudent(name, Username, Email, Passwordhash, Integer.parseInt(Classcode));
                if (worked){
                    
                    Login ToLoginScreen = new Login();  
                    ToLoginScreen.setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(this, "There has been an issue please retry", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                    jtxtName.setText("");
                    jtxtUsername.setText("");
                    jtxtEmail.setText("");
                    jtxtClassCode.setText("");
                    jtxtSchool.setText("");
                    jgetPassword.setText("");
                    jConfirmPassword.setText("");
                }
            }
            else if ( "Teacher".equals(user)){
                boolean worked = check.AddTeacher(name, Username, Email,  Passwordhash, School);
                if (worked){

                    Login ToLoginScreen = new Login();  
                    ToLoginScreen.setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(this, "There has been an issue please retry", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                    jtxtName.setText("");
                    jtxtUsername.setText("");
                    jtxtEmail.setText("");
                    jtxtClassCode.setText("");
                    jtxtSchool.setText("");
                    jgetPassword.setText("");
                    jConfirmPassword.setText("");
                }
                
            }
            else {
                JOptionPane.showMessageDialog(this, "There has been an issue please retry", "Try Again" ,JOptionPane.ERROR_MESSAGE);
                jtxtName.setText("");
                jtxtUsername.setText("");
                jtxtEmail.setText("");
                jtxtClassCode.setText("");
                jtxtSchool.setText("");
                jgetPassword.setText("");
                jConfirmPassword.setText("");
            }
        }
    }//GEN-LAST:event_jbuttonSubmitActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed

    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed

    }//GEN-LAST:event_jtxtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTellUserInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JLabel jLClassCode;
    private javax.swing.JLabel jLSchool;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JRadioButton jRadioStudent;
    private javax.swing.JRadioButton jRadioTeacher;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbuttonSubmit;
    private javax.swing.JPasswordField jgetPassword;
    private javax.swing.JTextField jtxtClassCode;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSchool;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
